sendToSqs:
  queue: 'name_of_the_queue'
  fileName: 'data/test/hello_world.xml'
  region: 'us-east-1'
  ratePerSec: 1
  duration: 2
  concurrentRequests: 1
  messageAttributes:
    - name: "orderNumber"
      value: "1234566"
      type: "string"